steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build"]
  secretEnv: ['GOOGLE_ANALYTICS_KEY', 'THUNDERFOREST_API_KEY', 'AUTH0_DOMAIN', 'AUTH0_CLIENT_ID', 'AUTH0_AUDIENCE', 'GOOGLE_API_KEY', 'SMTP_USERNAME', 'SMTP_PASSWORD', 'PATREON_ACCESS_TOKEN', 'PATREON_CAMPAIGN', 'STRAVA_CLIENT_ID', 'STRAVA_CLIENT_SECRET', 'STRAVA_REFRESH_TOKEN']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
availableSecrets:
  secretManager:
  - versionName: projects/409830855103/secrets/GOOGLE_ANALYTICS_KEY/versions/1
    env: 'GOOGLE_ANALYTICS_KEY'
  - versionName: projects/409830855103/secrets/THUNDERFOREST_API_KEY/versions/1
    env: 'THUNDERFOREST_API_KEY'
  - versionName: projects/409830855103/secrets/AUTH0_DOMAIN/versions/1
    env: 'AUTH0_DOMAIN'
  - versionName: projects/409830855103/secrets/AUTH0_CLIENT_ID/versions/1
    env: 'AUTH0_CLIENT_ID'
  - versionName: projects/409830855103/secrets/AUTH0_AUDIENCE/versions/1
    env: 'AUTH0_AUDIENCE'
  - versionName: projects/409830855103/secrets/GOOGLE_API_KEY/versions/1
    env: 'GOOGLE_API_KEY'
  - versionName: projects/409830855103/secrets/SMTP_USERNAME/versions/1
    env: 'SMTP_USERNAME'
  - versionName: projects/409830855103/secrets/SMTP_PASSWORD/versions/1
    env: 'SMTP_PASSWORD'
  - versionName: projects/409830855103/secrets/PATREON_ACCESS_TOKEN/versions/1
    env: 'PATREON_ACCESS_TOKEN'
  - versionName: projects/409830855103/secrets/PATREON_CAMPAIGN/versions/1
    env: 'PATREON_CAMPAIGN'
  - versionName: projects/409830855103/secrets/STRAVA_CLIENT_ID/versions/1
    env: 'STRAVA_CLIENT_ID'
  - versionName: projects/409830855103/secrets/STRAVA_CLIENT_SECRET/versions/1
    env: 'STRAVA_CLIENT_SECRET'
  - versionName: projects/409830855103/secrets/STRAVA_REFRESH_TOKEN/versions/1
    env: 'STRAVA_REFRESH_TOKEN'